# Generated by Django 3.0.5 on 2020-04-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSyncTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Finished', 'Finished')], default='Not Started', max_length=15)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to_sync', to='shipments.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerEndPointTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point_name', models.CharField(max_length=255)),
                ('remaining_req_limit', models.IntegerField()),
                ('limit_reset_at', models.DateTimeField()),
                ('initial_fbb_completed', models.BooleanField(default=False)),
                ('initial_fbr_completed', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Seller')),
            ],
            options={
                'unique_together': {('seller', 'end_point_name')},
            },
        ),
    ]
