# Generated by Django 3.0.5 on 2020-04-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.IntegerField()),
                ('pick_up_point', models.BooleanField()),
                ('shipment_date', models.DateTimeField()),
                ('shipment_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-shipment_date',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_id', models.IntegerField()),
                ('transporter_code', models.CharField(max_length=255)),
                ('track_and_trace', models.CharField(max_length=255)),
                ('shipping_label_id', models.IntegerField(null=True)),
                ('shipping_label_code', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point_name', models.CharField(blank=True, max_length=255)),
                ('saluation_code', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=255)),
                ('house_number_extended', models.CharField(blank=True, max_length=255)),
                ('address_supplement', models.CharField(blank=True, max_length=255)),
                ('extra_address_information', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
                ('chamber_of_commerce_number', models.CharField(blank=True, max_length=255)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('delivery_phone_number', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('latest_delivery_date', models.DateTimeField()),
                ('ean', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offer_condition', models.CharField(max_length=255)),
                ('offer_reference', models.CharField(blank=True, max_length=255)),
                ('fulfilment_method', models.CharField(max_length=3)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.Shipment')),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_shipments', to='shipments.UserData'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.UserData'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.Seller'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transported_shipments', to='shipments.Transport'),
        ),
    ]
