# Generated by Django 3.0.5 on 2020-04-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_req_limit', models.IntegerField()),
                ('limit_reset_at', models.DateTimeField()),
                ('initial_scan_completed', models.BooleanField(default=False)),
                ('sellar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipments.SellerShop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetailSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_req_limit', models.IntegerField()),
                ('limit_reset_at', models.DateTimeField()),
                ('sellar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipments.SellerShop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=255)),
                ('fulfilment_method', models.CharField(max_length=3)),
                ('state', models.SmallIntegerField(choices=[(0, 'Not Started'), (1, 'Started'), (2, 'Finished')], default=0)),
                ('data', models.TextField()),
                ('sellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.SellerShop')),
            ],
        ),
    ]
